import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createStore,applyWeekChange,undoLast,completionMetric,createGrowth,creditGrowth,validXP,revokeGrowth,normalizeEndpoint} from '../reference/rules.mjs';
const state=JSON.parse(readFileSync(new URL('../contracts/sample-state.json',import.meta.url)));
const request=JSON.parse(readFileSync(new URL('../contracts/sample-week-change.json',import.meta.url)));
const fixture=()=>[createStore(state),structuredClone(request)];
const rejects=(name,mutate,code)=>test(name,()=>{const [s,r]=fixture();mutate(s,r);const before=structuredClone(s);assert.throws(()=>applyWeekChange(s,r),new RegExp(code));assert.deepEqual(s,before)});
test('10h→4h: capacity holds and task definitions survive',()=>{const[s,r]=fixture();const a=applyWeekChange(s,r);assert.equal(a.scheduledMinutes,240);assert.equal(s.state.tasks.length,5);assert.equal(s.state.version,5);assert.equal(s.audit.length,1);assert.equal(s.state.outcome,state.outcome)});
test('idempotent request does not append audit',()=>{const[s,r]=fixture();applyWeekChange(s,r);assert.equal(applyWeekChange(s,r).replayed,true);assert.equal(s.audit.length,1)});
test('key order does not defeat canonical idempotency',()=>{const[s,r]=fixture();applyWeekChange(s,r);assert.equal(applyWeekChange(s,Object.fromEntries(Object.entries(r).reverse())).replayed,true)});
test('same request id with different content rejected',()=>{const[s,r]=fixture();applyWeekChange(s,r);r.reason='new';assert.throws(()=>applyWeekChange(s,r),/ID_REUSED/)});
rejects('stale version cannot overwrite',(_,r)=>r.baseVersion--,'STALE');
rejects('different plan cannot be patched',(_,r)=>r.planId='other','STALE');
rejects('initial auto-adjust consent required',(s)=>s.state.autoAdjust=false,'NOT_AUTHORIZED');
rejects('model cannot add arbitrary authority field',(_,r)=>r.approved=true,'SHAPE');
rejects('high-level goal operation rejected',(_,r)=>r.actions[0].type='change_goal','OPERATION');
rejects('arbitrary SQL path rejected',(_,r)=>r.actions[0].path='finance.cash','SHAPE');
rejects('locked responsibility protected',(s)=>s.state.tasks[2].pinned=true,'PROTECTED');
rejects('completed record protected',(s)=>s.state.tasks[2].completed=true,'PROTECTED');
rejects('hard deadline cannot silently be unscheduled',(s)=>s.state.tasks[2].hardDue='2026-09-25','HARD_DUE');
rejects('unknown task rejected',(_,r)=>r.actions[0].taskId='missing','UNKNOWN_TASK');
rejects('duplicate target rejected',(_,r)=>r.actions.push(structuredClone(r.actions[0])),'DUPLICATE_TARGET');
rejects('batch rejection rolls back prior legal actions',(_,r)=>r.actions[2].type='delete_task','OPERATION');
rejects('capacity remains hard bound',(s)=>s.state.capacityMinutes=100,'CAPACITY');
rejects('negative capacity invalid',(s)=>s.state.capacityMinutes=-1,'CAPACITY');
rejects('cross-week reschedule requires proposal',(_,r)=>r.actions[0]={type:'schedule_task',taskId:'t3',date:'2026-09-30',rank:3},'OUT_OF_WEEK');
rejects('invalid date fails closed',(_,r)=>r.actions[0]={type:'schedule_task',taskId:'t3',date:'2026-09-99',rank:3},'OUT_OF_WEEK');
rejects('unschedule action must use null',(_,r)=>r.actions[0].date='2026-09-23','SHAPE');
rejects('rank must be integer',(_,r)=>r.actions[0].rank=1.5,'SHAPE');
rejects('second primary focus rejected',(s)=>s.state.primaryProjects.push('second'),'MULTIPLE_PRIMARY');
rejects('dependency cannot be removed beneath active task',(_,r)=>r.actions.push({type:'unschedule_task',taskId:'t1',date:null,rank:0}),'DEPENDENCY');
test('undo appends compensation and restores schedule',()=>{const[s,r]=fixture();s.state.capacityMinutes=600;applyWeekChange(s,r);assert.equal(undoLast(s,5),6);assert.deepEqual(s.state.tasks,state.tasks);assert.equal(s.audit.length,2)});
test('undo rejects intervening edit',()=>{const[s,r]=fixture();applyWeekChange(s,r);s.state.version++;assert.throws(()=>undoLast(s,5),/UNDO_CONFLICT/)});
test('old request cannot be reapplied after undo',()=>{const[s,r]=fixture();s.state.capacityMinutes=600;applyWeekChange(s,r);undoLast(s,5);applyWeekChange(s,r);assert.equal(s.state.version,6);assert.deepEqual(s.state.tasks,state.tasks)});
test('no records means unknown, not failure',()=>assert.equal(completionMetric([]).rate,null));
test('insufficient coverage does not produce a performance rate',()=>assert.equal(completionMetric([{status:'completed'},{status:'unknown'}]).rate,null));
test('cancelled is not completed; partial is not fully completed',()=>assert.equal(completionMetric([{status:'completed'},{status:'partial'},{status:'cancelled'}]).rate,0.5));
test('review reward is capped and de-duplicated',()=>{const g=createGrowth();assert.equal(creditGrowth(g,{type:'review',sourceId:'r1',confirmed:true},'2026-W39'),10);assert.equal(creditGrowth(g,{type:'review',sourceId:'r1',confirmed:true},'2026-W39'),0);assert.equal(creditGrowth(g,{type:'review',sourceId:'r2',confirmed:true},'2026-W39'),0)});
test('same evidence cannot be rewarded next week',()=>{const g=createGrowth();const e={type:'milestone',sourceId:'m1',confirmed:true};creditGrowth(g,e,'2026-W39');assert.equal(creditGrowth(g,e,'2026-W40'),0)});
test('unconfirmed evidence receives no XP',()=>assert.equal(creditGrowth(createGrowth(),{type:'milestone',sourceId:'m1',confirmed:false},'2026-W39'),0));
test('recovery toggles and task ticks receive no XP',()=>{const g=createGrowth();for(const type of ['recovery','task_completed','timer'])assert.equal(creditGrowth(g,{type,sourceId:type,confirmed:true},'2026-W39'),0)});
test('weekly cap bounds milestone farming',()=>{const g=createGrowth();for(let i=0;i<20;i++)creditGrowth(g,{type:'milestone',sourceId:'m'+i,confirmed:true},'2026-W39');assert.equal(validXP(g),60)});
test('correction lowers valid XP but never reached stage',()=>{const g=createGrowth();for(let i=0;i<4;i++)creditGrowth(g,{type:'milestone',sourceId:'m'+i,confirmed:true},'2026-W'+(39+i));assert.equal(g.highestStage,2);for(const e of g.events)revokeGrowth(g,e.key);assert.equal(validXP(g),0);assert.equal(g.highestStage,2);assert.equal(creditGrowth(g,{type:'milestone',sourceId:'m0',confirmed:true},'2026-W45'),0)});
test('API root preserves /v1 with no duplication',()=>assert.equal(normalizeEndpoint('https://example.com/v1/'),'https://example.com/v1/chat/completions'));
test('custom proxy path preserved',()=>assert.equal(normalizeEndpoint('https://example.com/team/api/'),'https://example.com/team/api/chat/completions'));
test('loopback HTTP needs explicit local consent',()=>{assert.throws(()=>normalizeEndpoint('http://127.0.0.1:11434/v1'),/HTTPS_REQUIRED/);assert.equal(normalizeEndpoint('http://127.0.0.1:11434/v1',true),'http://127.0.0.1:11434/v1/chat/completions')});
test('remote HTTP disallowed even with local flag',()=>assert.throws(()=>normalizeEndpoint('http://example.com/v1',true),/HTTPS_REQUIRED/));
test('credential in URL rejected',()=>assert.throws(()=>normalizeEndpoint('https://user:secret@example.com/v1'),/BAD_URL/));
test('query in API root rejected',()=>assert.throws(()=>normalizeEndpoint('https://example.com/v1?key=demo'),/BAD_URL/));
test('full completion endpoint not mistaken for API root',()=>assert.throws(()=>normalizeEndpoint('https://example.com/v1/chat/completions'),/API_ROOT_REQUIRED/));

test('undo must not exceed currently approved capacity',()=>{const[s,r]=fixture();applyWeekChange(s,r);assert.throws(()=>undoLast(s,5),/UNDO_CAPACITY_CONFLICT/)});
test('request IDs cannot alter receipt object prototypes',()=>{const[s,r]=fixture();r.requestId='__proto__';applyWeekChange(s,r);assert.equal(applyWeekChange(s,r).replayed,true);assert.equal(s.receipts.size,1)});
